# Generated by Django 2.2 on 2021-01-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_barang', '0002_auto_20210111_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='gambar',
            field=models.ImageField(upload_to='static/daftar_barang/barang'),
        ),
    ]
