# Generated by Django 2.2 on 2021-01-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_barang', '0003_auto_20210111_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='gambar',
            field=models.ImageField(upload_to='barang'),
        ),
    ]
