# Generated by Django 2.2 on 2021-01-11 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_barang', '0004_auto_20210111_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='gambar',
        ),
        migrations.AddField(
            model_name='barang',
            name='kadaluarsa',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='barang',
            name='merk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
